// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2a7bzOFpbQTqVLj-Qf1dcfJLVToLZWs',
    appId: '1:886374537264:android:2d95a743add7f03dbb35f5',
    messagingSenderId: '886374537264',
    projectId: 'final-uni-project-ccdcf',
    databaseURL: 'https://final-uni-project-ccdcf-default-rtdb.firebaseio.com',
    storageBucket: 'final-uni-project-ccdcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVz3VymA3U6Cmn53MJPwM0yOaqKLKj9cQ',
    appId: '1:886374537264:ios:b6caf51728b62b84bb35f5',
    messagingSenderId: '886374537264',
    projectId: 'final-uni-project-ccdcf',
    databaseURL: 'https://final-uni-project-ccdcf-default-rtdb.firebaseio.com',
    storageBucket: 'final-uni-project-ccdcf.appspot.com',
    androidClientId: '886374537264-5d1o8ck774q82rft4hr762ak0ljpp58h.apps.googleusercontent.com',
    iosClientId: '886374537264-6mim8di02sk6rbvh2dqgd2lk8c8kq2gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.es2al',
  );
}
